apiVersion: v1
kind: Secret
metadata:
  name: chunkmydocs-secrets
  namespace: chunkmydocs
type: Opaque
stringData:
  AUTH__KEYCLOAK_URL: http://keycloak:8080
  AWS__ACCESS_KEY: minioadmin
  AWS__ENDPOINT: http://minio:9000
  AWS__PRESIGNED_URL_ENDPOINT: http://localhost:9000
  AWS__REGION: us-east-1
  AWS__SECRET_KEY: minioadmin
  LLM__KEY: # Add your OpenAI key here
  PG__URL: postgresql://postgres:postgres@postgres:5432/chunkr
  REDIS__URL: redis://redis:6379
  RRQ__URL: http://rrq:8000
  SEARCH__DENSE_VECTOR_URL: http://dense-vector:80
  WORKER__GENERAL_OCR_URL: http://doctr:8000
  WORKER__PDLA_FAST_URL: http://pdla:8000
  WORKER__PDLA_URL: http://pdla:8000
  WORKER__TABLE_OCR_URL: http://table-ocr:8000
  VITE_API_URL: http://localhost:8000
  VITE_KEYCLOAK_CLIENT_ID: chunkr
  VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URI: http://localhost:5173
  VITE_KEYCLOAK_REALM: chunkr
  VITE_KEYCLOAK_REDIRECT_URI: http://localhost:5173
  VITE_KEYCLOAK_URL: http://localhost:8080

