apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: chunkmydocs
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_PROXY: "edge"
  KC_HOSTNAME: "auth.chunkmydocs.com"
  KC_FEATURES: "hostname:v2"
  KC_HOSTNAME_DEBUG: "true"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://{DB_HOST}:{DB_PORT}/keycloak"
  KC_DB_USERNAME: "postgres"
  KC_DB_PASSWORD: "password"
              