apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: chunkmydocs
type: Opaque
stringData:
  VITE_API_URL: "https://api.example.com"
  VITE_KEYCLOAK_URL: "https://auth.example.com"
  VITE_KEYCLOAK_REALM: "your-realm-name"
  VITE_KEYCLOAK_CLIENT_ID: "your-client-id"
  VITE_KEYCLOAK_REDIRECT_URI: "https://www.example.com"
  VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URI: "https://www.example.com"
  VITE_STRIPE_API_KEY: "your-stripe-api-key"
