apiVersion: v1
kind: Service
metadata:
  name: chunkmydocs-service
  labels:
    app.kubernetes.io/name: chunkmydocs
spec:
  selector:
    app.kubernetes.io/name: chunkmydocs
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP