# .llm_providers.yaml.example
# Copy this file to .llm_providers.yaml within core and configure your allowed LLM providers.
# Ensure the corresponding API key environment variables (api_key_env_var) are set.
providers:
  - id: openrouter
    url: https://openrouter.ai/api/v1/chat/completions
    models:
      - google/gemini-2.0-flash-001
    api_key_env_var: LLM__KEY_OPENROUTER # e.g., set LLM__KEY_OPENROUTER in .env
  # - id: another_provider
  #   url: https://api.another-provider.com/v1/chat/completions
  #   models:
  #     - model-slug-1
  #     - model-slug-2
  #   api_key_env_var: LLM__KEY_ANOTHER_PROVIDER