/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BoundingBox : Bounding box for an item. It is used for chunks, segments and OCR results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoundingBox {
    /// The height of the bounding box.
    #[serde(rename = "height")]
    pub height: f32,
    /// The left coordinate of the bounding box.
    #[serde(rename = "left")]
    pub left: f32,
    /// The top coordinate of the bounding box.
    #[serde(rename = "top")]
    pub top: f32,
    /// The width of the bounding box.
    #[serde(rename = "width")]
    pub width: f32,
}

impl BoundingBox {
    /// Bounding box for an item. It is used for chunks, segments and OCR results.
    pub fn new(height: f32, left: f32, top: f32, width: f32) -> BoundingBox {
        BoundingBox {
            height,
            left,
            top,
            width,
        }
    }
}

