/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EmbedSource {
    #[serde(rename = "HTML")]
    Html,
    #[serde(rename = "Markdown")]
    Markdown,
    #[serde(rename = "LLM")]
    Llm,
    #[serde(rename = "Content")]
    Content,

}

impl std::fmt::Display for EmbedSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Html => write!(f, "HTML"),
            Self::Markdown => write!(f, "Markdown"),
            Self::Llm => write!(f, "LLM"),
            Self::Content => write!(f, "Content"),
        }
    }
}

impl Default for EmbedSource {
    fn default() -> EmbedSource {
        Self::Html
    }
}

