/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FallbackStrategyOneOf : Use a specific model as fallback
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FallbackStrategyOneOf {
    /// Use a specific model as fallback
    #[serde(rename = "Model")]
    pub model: String,
}

impl FallbackStrategyOneOf {
    /// Use a specific model as fallback
    pub fn new(model: String) -> FallbackStrategyOneOf {
        FallbackStrategyOneOf {
            model,
        }
    }
}

