/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FallbackStrategyOneOf1 : Use the system default fallback model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FallbackStrategyOneOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl FallbackStrategyOneOf1 {
    /// Use the system default fallback model
    pub fn new(r#type: Type) -> FallbackStrategyOneOf1 {
        FallbackStrategyOneOf1 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Default")]
    Default,
}

impl Default for Type {
    fn default() -> Type {
        Self::Default
    }
}

