/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GenerationStrategy {
    #[serde(rename = "LLM")]
    Llm,
    #[serde(rename = "Auto")]
    Auto,

}

impl std::fmt::Display for GenerationStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Llm => write!(f, "LLM"),
            Self::Auto => write!(f, "Auto"),
        }
    }
}

impl Default for GenerationStrategy {
    fn default() -> GenerationStrategy {
        Self::Llm
    }
}

