/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LlmProcessingFallbackStrategy {
    /// The fallback strategy to use for the LLMs in the task.
    FallbackStrategy(Box<models::FallbackStrategy>),
}

impl Default for LlmProcessingFallbackStrategy {
    fn default() -> Self {
        Self::FallbackStrategy(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Model")]
    Model,
}

impl Default for Type {
    fn default() -> Type {
        Self::Model
    }
}

