/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OcrStrategy : Controls the Optical Character Recognition (OCR) strategy. - `All`: Processes all pages with OCR. (Latency penalty: ~0.5 seconds per page) - `Auto`: Selectively applies OCR only to pages with missing or low-quality text. When text layer is present the bounding boxes from the text layer are used.
/// Controls the Optical Character Recognition (OCR) strategy. - `All`: Processes all pages with OCR. (Latency penalty: ~0.5 seconds per page) - `Auto`: Selectively applies OCR only to pages with missing or low-quality text. When text layer is present the bounding boxes from the text layer are used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OcrStrategy {
    #[serde(rename = "All")]
    All,
    #[serde(rename = "Auto")]
    Auto,

}

impl std::fmt::Display for OcrStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::All => write!(f, "All"),
            Self::Auto => write!(f, "Auto"),
        }
    }
}

impl Default for OcrStrategy {
    fn default() -> OcrStrategy {
        Self::All
    }
}

