/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TokenizerTypeOneOf1 : Use any Hugging Face tokenizer by specifying its model ID Examples: \"Qwen/Qwen-tokenizer\", \"facebook/bart-large\"
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenizerTypeOneOf1 {
    /// Use any Hugging Face tokenizer by specifying its model ID Examples: \"Qwen/Qwen-tokenizer\", \"facebook/bart-large\"
    #[serde(rename = "String")]
    pub string: String,
}

impl TokenizerTypeOneOf1 {
    /// Use any Hugging Face tokenizer by specifying its model ID Examples: \"Qwen/Qwen-tokenizer\", \"facebook/bart-large\"
    pub fn new(string: String) -> TokenizerTypeOneOf1 {
        TokenizerTypeOneOf1 {
            string,
        }
    }
}

