/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TokenizerTypeOneOf : Use one of the predefined tokenizer types
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenizerTypeOneOf {
    /// Use one of the predefined tokenizer types
    #[serde(rename = "Enum")]
    pub r#enum: models::Tokenizer,
}

impl TokenizerTypeOneOf {
    /// Use one of the predefined tokenizer types
    pub fn new(r#enum: models::Tokenizer) -> TokenizerTypeOneOf {
        TokenizerTypeOneOf {
            r#enum,
        }
    }
}

