/*
 * Chunkr API
 *
 * API service for document layout analysis and chunking to convert document into RAG/LLM-ready data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ishaan@lumina.sh
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateFormMultipartChunkProcessing {
    ChunkProcessing(Box<models::ChunkProcessing>),
}

impl Default for UpdateFormMultipartChunkProcessing {
    fn default() -> Self {
        Self::ChunkProcessing(Default::default())
    }
}

