apiVersion: v1
kind: Secret
metadata:
  name: chunkr-secret
type: Opaque
stringData:
  AUTH__KEYCLOAK_URL: # Add your auth url here
  AWS__ACCESS_KEY: # Add your AWS access key here
  AWS__REGION: # Add your AWS region here
  AWS__SECRET_KEY: # Add your AWS secret key here
  LLM__KEY: # Add your OpenAI key here
  REDIS__URL: # Add your Redis URL here
