apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
type: Opaque
stringData:
  VITE_API_URL: # Add your chunkr api url here
  VITE_KEYCLOAK_CLIENT_ID: chunkr
  VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URI: # Add your web url here
  VITE_KEYCLOAK_REALM: chunkr
  VITE_KEYCLOAK_REDIRECT_URI: # Add your web url here
  VITE_KEYCLOAK_URL: # Add your auth url here
