// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 5578af999b3458a7a3108009ea384f4294ce495e7550e9b61aaf996aed2dd9fa


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

export function KcPage(_props: { kcContext: any; }){
    return null;
}

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}
