apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess
  labels:
    app.kubernetes.io/name: preprocess
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: preprocess
  template:
    metadata:
    
      labels:
        app.kubernetes.io/name: preprocess
    spec:
      containers:
      - name: preprocess
        image: luminainc/preprocess:68a05839 
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: chunkr-secrets
        env:
        - name: PG__POOL__MAX_SIZE
          value: "3"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
