ingress:
  enabled: true
  type: "cloudflare" # can be "cloudflare" or "nginx"
  className: "cloudflare"
  annotations:
    kubernetes.io/ingress.class: nginx
  domain: "chunkr.ai"
  subdomains:
    root: true
  tls:
    enabled: false
    secretName: "tls-secret"
  cloudflare:
    enabled: true
    replicas: 2
    image:
      repository: cloudflare/cloudflared
      tag: "2024.12.1"
      pullPolicy: Always
    config:
      tunnelName: "chunkr"
      services:
        - name: "server"
        - name: "keycloak"
        - name: "web"
        - name: "minio"
        - name: "embeddings"
        - name: "reranker"
        - name: "analytics-web"
        - name: "analytics-server"

services:
  server:
    enabled: true
    useStandardEnv: true
    image:
      repository: server-azure
      tag: "7fa7ddf0"
    imagePullSecrets:
      - name: regcred
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: "api"
    envFrom:
      - secretRef:
          name: chunkr-secret

  task:
    enabled: true
    useStandardEnv: true
    image:
      repository: task-azure
      tag: "7fa7ddf0"
    imagePullSecrets:
      - name: regcred
    envFrom:
      - secretRef:
          name: chunkr-secret
    env:
      - name: PG__POOL__MAX_SIZE
        value: "3"

  web:
    enabled: true
    image:
      repository: web
      tag: "952c273a"
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: "www"
    env:
      - name: VITE_API_URL
        value: https://{{ .Values.services.server.ingress.subdomain }}.{{ .Values.ingress.domain }}
      - name: VITE_FEATURE_FLAG_PIPELINE
        value: "true"
      - name: VITE_KEYCLOAK_CLIENT_ID
        value: chunkr
      - name: VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URI
        value: https://{{ .Values.services.web.ingress.subdomain }}.{{ .Values.ingress.domain }}
      - name: VITE_KEYCLOAK_REALM
        value: chunkr
      - name: VITE_KEYCLOAK_REDIRECT_URI
        value: https://{{ .Values.services.web.ingress.subdomain }}.{{ .Values.ingress.domain }}
      - name: VITE_KEYCLOAK_URL
        value: https://{{ .Values.services.keycloak.ingress.subdomain }}.{{ .Values.ingress.domain }}

  analytics-web:
    enabled: true
    image:
      repository: analytics-web
      tag: "31a71c56"
    imagePullSecrets:
      - name: regcred
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: "analytics"
    env:
      - name: VITE_API_URL
        value: https://{{ index .Values.services "analytics-server" "ingress" "subdomain" }}.{{ .Values.ingress.domain }}
      - name: VITE_API_KEY
        valueFrom:
          secretKeyRef:
            name: chunkr-secret
            key: ANALYTICS__API_KEY

  analytics-server:
    enabled: true
    image:
      repository: analytics-server
      tag: "3096be45"
    imagePullSecrets:
      - name: regcred
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: "analytics-api"
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: chunkr-secret
            key: ANALYTICS__API_KEY
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: chunkr-secret
            key: PG__URL

  reranker:
    enabled: false
    image:
      repository: text-embeddings-inference
      tag: "1.6"
      registry: ghcr.io/huggingface
    ingress:
      enabled: false
      subdomain: "rerank"
    port: 8000
    targetPort: 80
    args: [ "--model-id", "BAAI/bge-reranker-large", "--auto-truncate", "--payload-limit", "100000000" ]
    useGPU: true
    labels:
      workload-type: chunkr-gpu