apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: TUNNEL_TOKEN
          args:
            - tunnel
            - --no-autoupdate
            - run
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    ingress:
      - service: http://chunkr-service:80
      - service: http://keycloak-service:80
      - service: http://rrq-analytics-service:80
      - service: http://web-service:80
      - service: http_status:404
