apiVersion: v1
kind: Service
metadata:
  name: pdla-service
  namespace: chunkmydocs
  labels:
    app.kubernetes.io/name: pdla
  annotations:
    cloud.google.com/backend-config: '{"default": "pdla-backendconfig"}'
spec:
  selector:
    app.kubernetes.io/name: pdla
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: pdla-backendconfig
  namespace: chunkmydocs
spec:
  timeoutSec: 10000