apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunkr-secrets-keeper
  namespace: chunkr
  labels:
    app: chunkr-secrets-keeper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chunkr-secrets-keeper
  template:
    metadata:
      labels:
        app: chunkr-secrets-keeper
    spec:
      containers:
      - name: secrets-keeper
        image: busybox:latest
        command: 
          - /bin/sh
          - -c
          - |
            echo "Starting secrets keeper pod..."
            echo "Secrets mounted at: /mnt/secrets-store"
            ls -la /mnt/secrets-store/
            # Keep the pod running to maintain secret sync
            while true; do
              echo "Keeper pod is running - $(date)"
              sleep 300  # Check every 5 minutes
            done
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Add readiness probe to ensure secrets are mounted
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test -d /mnt/secrets-store && ls /mnt/secrets-store/ | wc -l | grep -v '^0$'"
          initialDelaySeconds: 10
          periodSeconds: 30
        # Add liveness probe to restart if container becomes unresponsive
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Liveness check passed'"
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: chunkr
      # Add node affinity to spread replicas across different nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - chunkr-secrets-keeper
              topologyKey: kubernetes.io/hostname 