apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: chunkr
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "d90a47c7-9b9e-41df-85d8-67ae358af744"
    keyvaultName: "mgx-chunkr-keyvault"
    objects: |
      array:
        - |
          objectName: AWS-ACCESS-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: AWS-SECRET-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURE-ENDPOINT
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURE-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: KC-DB-URL
          objectType: secret
          objectVersion: ""
        - |
          objectName: KC-DB-USERNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: KC-DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: PG-URL
          objectType: secret
          objectVersion: ""
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
          objectVersion: ""
    tenantId: "50e9b74b-00a7-4ac3-984c-3484482d7ba9"
  secretObjects:
    - secretName: chunkr-secret
      type: Opaque
      data:
        - key: AWS__ACCESS_KEY
          objectName: AWS-ACCESS-KEY
        - key: AWS__SECRET_KEY
          objectName: AWS-SECRET-KEY
        - key: AZURE__ENDPOINT
          objectName: AZURE-ENDPOINT
        - key: AZURE__KEY
          objectName: AZURE-KEY
        - key: KC_DB_URL
          objectName: KC-DB-URL
        - key: KC_DB_USERNAME
          objectName: KC-DB-USERNAME
        - key: KC_DB_PASSWORD
          objectName: KC-DB-PASSWORD
        - key: PG__URL
          objectName: PG-URL
        - key: LLM__KEY
          objectName: OPENAI-API-KEY
