ingress:
  enabled: true
  type: cloudflare
  className: cloudflare
  annotations:
    kubernetes.io/ingress.class: nginx
  domain: chunkr.ai
  subdomains:
    root: true
  tls:
    enabled: false
    secretName: tls-secret
  cloudflare:
    enabled: true
    replicas: 2
    image:
      repository: cloudflare/cloudflared
      tag: 2025.2.0
      pullPolicy: Always
    config:
      tunnelName: chunkr
      services:
        - name: server
        - name: keycloak
        - name: web
        - name: minio
common:
  standardEnv:
    - name: AUTH__KEYCLOAK_URL
      value: >-
        https://{{ .Values.services.keycloak.ingress.subdomain }}.{{
        .Values.ingress.domain }}
    - name: AWS__ENDPOINT
      value: http://{{- .Release.Name }}-minio:9000
    - name: AWS__PRESIGNED_URL_ENDPOINT
      value: >-
        https://{{ .Values.services.minio.ingress.subdomain }}.{{
        .Values.ingress.domain }}
    - name: AWS__REGION
      value: us-east-1
    - name: JOB__TASK_TIMEOUT
      value: "600"
    - name: REDIS__URL
      value: redis://{{- .Release.Name }}-redis:6379
    - name: SEARCH__DENSE_VECTOR_URL
      value: http://{{- .Release.Name }}-embeddings:8000
    - name: WORKER__GENERAL_OCR_URL
      value: http://{{- .Release.Name }}-ocr:8000
    - name: WORKER__SEGMENTATION_URL
      value: http://{{- .Release.Name }}-segmentation:8000
    - name: WORKER__SERVER_URL
      value: >-
        https://{{ .Values.services.server.ingress.subdomain }}.{{
        .Values.ingress.domain }}
    - name: EMAIL__SERVER_URL
      value: http://{{- .Release.Name }}-emails:8000
    - name: LLM__MODEL
      value: gpt-4.1-mini-2025-04-14
    - name: LLM__FALLBACK_MODEL
      value: gpt-4o-2024-08-06
    - name: LLM__URL
      value: https://api.openai.com/v1/chat/completions
global:
  image:
    registry: luminainc
    pullPolicy: Always
  storageClass: standard
  gpuWorkload:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: workload-type
                    operator: In
                    values:
                      - chunkr-gpu
              topologyKey: kubernetes.io/hostname
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 5Gi
    volumeMounts:
      - name: dshm
        mountPath: /dev/shm
nvidia:
  timeSlicing:
    enabled: true
    replicas: 8
    timeSlice: 2ms
services:
  server:
    enabled: true
    useStandardEnv: true
    image:
      repository: server-azure
      tag: 1.14.0-enterprise
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: api
    envFrom:
      - secretRef:
          name: chunkr-secret
          optional: true
    volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: chunkr
      - name: llm-models-config
        configMap:
          name: llm-models-configmap
    volumeMounts:
      - name: llm-models-config
        mountPath: /app/models.yaml
        subPath: models.yaml
        readOnly: true
  task:
    enabled: true
    useStandardEnv: true
    image:
      repository: task-azure
      tag: 1.14.0-enterprise
    envFrom:
      - secretRef:
          name: chunkr-secret
          optional: true
    volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: chunkr
      - name: llm-models-config
        configMap:
          name: llm-models-configmap
    volumeMounts:
      - name: llm-models-config
        mountPath: /app/models.yaml
        subPath: models.yaml
        readOnly: true
  web:
    enabled: true
    image:
      repository: web
      tag: 1.14.0-enterprise
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: www
    env:
      - name: VITE_API_URL
        value: >-
          https://{{ .Values.services.server.ingress.subdomain }}.{{
          .Values.ingress.domain }}
      - name: VITE_DOCS_URL
        value: https://docs.chunkr.ai
      - name: VITE_FEATURE_FLAG_PIPELINE
        value: "true"
      - name: VITE_KEYCLOAK_CLIENT_ID
        value: chunkr
      - name: VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URI
        value: >-
          https://{{ .Values.services.web.ingress.subdomain }}.{{
          .Values.ingress.domain }}
      - name: VITE_KEYCLOAK_REALM
        value: chunkr
      - name: VITE_KEYCLOAK_REDIRECT_URI
        value: >-
          https://{{ .Values.services.web.ingress.subdomain }}.{{
          .Values.ingress.domain }}/dashboard
      - name: VITE_KEYCLOAK_URL
        value: >-
          https://{{ .Values.services.keycloak.ingress.subdomain }}.{{
          .Values.ingress.domain }}
      - name: VITE_STRIPE_API_KEY
        value: "100"
    volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: chunkr
  ocr:
    enabled: false
    image:
      repository: doctr
      tag: 1.11.0-enterprise
    imagePullSecrets:
      - name: regcred
    port: 8000
    targetPort: 8000
    useGPU: true
    enableTopologySpreadConstraints: true
    env:
      - name: MAX_BATCH_SIZE
        value: "100"
    labels:
      workload-type: chunkr-gpu
  segmentation:
    enabled: true
    image:
      repository: segmentation
      tag: 1.5.0
    imagePullSecrets:
      - name: regcred
    port: 8000
    targetPort: 8000
    useGPU: true
    enableTopologySpreadConstraints: true
    labels:
      workload-type: chunkr-gpu
  analytics-web:
    enabled: false
    image:
      repository: analytics-web
      tag: 1.11.0-enterprise
    imagePullSecrets:
      - name: regcred
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: analytics
    env:
      - name: VITE_API_URL
        value: >-
          https://{{ index .Values.services "analytics-server" "ingress"
          "subdomain" }}.{{ .Values.ingress.domain }}
  analytics-server:
    enabled: false
    image:
      repository: analytics-server
      tag: 1.11.0-enterprise
    imagePullSecrets:
      - name: regcred
    port: 8000
    targetPort: 8000
    ingress:
      enabled: true
      subdomain: analytics-api
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: chunkr-secret
            key: ANALYTICS-API-KEY
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: chunkr-secret
            key: PG-URL
  cleanup-failed-pods:
    enabled: false
    type: cronjob
    schedule: "*/15 * * * *"
    image:
      registry: bitnami
      repository: kubectl
      tag: 1.14.0-enterprise
    command:
      - kubectl
    args:
      - delete
      - pods
      - "--field-selector=status.phase=Failed"
      - "-n"
      - chunkr
    serviceAccountName: default
    podSpec:
      restartPolicy: OnFailure
