apiVersion: v1
kind: Secret
metadata:
  name: luminadockerhub
  namespace: sf-lumina
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "${LUMINA_DOCKERHUB_USERNAME}",
          "password": "${LUMINA_DOCKERHUB_PASSWORD}"
        }
      }
    }
