apiVersion: v1
kind: Secret
metadata:
  name: qwen-vl-training-secrets
type: Opaque
stringData:
  OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
  CHUNKR_API_KEY: "${CHUNKR_API_KEY}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  S3_BUCKET: "${S3_BUCKET}"
  DATASET_NAME: "${DATASET_NAME}"
  HF_TOKEN: "${HF_TOKEN}"
  LUMINA_DOCKERHUB_USERNAME: "${LUMINA_DOCKERHUB_USERNAME}"
  LUMINA_DOCKERHUB_PASSWORD: "${LUMINA_DOCKERHUB_PASSWORD}"
