apiVersion: v1
kind: Service
metadata:
  name: table-ocr-service
  namespace: chunkmydocs
  labels:
    app.kubernetes.io/name: table-ocr
spec:
  selector:
    app.kubernetes.io/name: table-ocr
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
