[project]
name = "load-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chunkr-ai>=0.0.41",
    "honcho>=2.0.0",
    "matplotlib>=3.9.4",
    "redis>=5.2.1",
    "ruff>=0.9.3",
    "seaborn>=0.13.2",
]
