apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-standard-env
  labels:
    {{- include "chunkr.labels" . | nindent 4 }}
data:
  {{- range .Values.common.standardEnv }}
  {{ .name }}: {{ tpl .value $ | quote }}
  {{- end }} 