{{- if and .Values.ingress.enabled (eq .Values.ingress.type "nginx") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "chunkr.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- if .Values.ingress.subdomains.root }}
    - {{ .Values.ingress.domain }}
    {{- end }}
    {{- range $serviceName, $service := .Values.services }}
    {{- if and (hasKey $service "ingress") $service.ingress.enabled }}
    - {{ printf "%s.%s" $service.ingress.subdomain $.Values.ingress.domain }}
    {{- end }}
    {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  {{- if .Values.ingress.subdomains.root }}
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-web
            port:
              number: {{ .Values.services.web.port }}
  {{- end }}
  
  {{- range $serviceName, $service := .Values.services }}
  {{- if and (hasKey $service "ingress") $service.ingress.enabled }}
  - host: {{ printf "%s.%s" $service.ingress.subdomain $.Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-{{ $serviceName }}
            port:
              number: {{ $service.port }}
  {{- end }}
  {{- end }}
{{- end }}