apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-quality
  labels:
    app.kubernetes.io/name: high-quality
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: high-quality
  template:
    metadata:
    
      labels:
        app.kubernetes.io/name: high-quality
    spec:
      containers:
      - name: high-quality
        image: luminainc/high-quality:68a05839 
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: chunkr-secret
        env:
        - name: PG__POOL__MAX_SIZE
          value: "3"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
