[project]
name = "reranker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flagembedding>=1.2.11",
    "flask>=3.0.3",
    "peft>=0.13.2",
    "pydantic>=2.9.2",
    "python-dotenv>=1.0.1",
    "robyn>=0.62.1",
]
