from enum import Enum


class TableOfContentType(Enum):
    INDENTATION_0 = "INDENTATION_0"
    INDENTATION_1 = "INDENTATION_1"
    INDENTATION_2 = "INDENTATION_2"
    INDENTATION_3 = "INDENTATION_3"
