apiVersion: v1
kind: Service
metadata:
  name: embeddings-service
  namespace: chunkmydocs
  labels:
    app.kubernetes.io/name: embeddings
spec:
  selector:
    app.kubernetes.io/name: embeddings
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
